version: '3'
services:
  influxdb:
    image: influxdb
    # ports:
    #   - '6379'
    # networks:
    #   - frontend
    # deploy:
    #   replicas: 2
    #   update_config:
    #     parallelism: 2
    #     delay: 10s
    #   restart_policy:
    #     condition: on-failure
  nodered:
    image: nodered/node-red
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    # networks:
    #   - backend
    # deploy:
    #   placement:
    #     constraints: [node.role == manager]
  telegraf:
    image: telegraf
    # ports:
    #   - 5000:80
    # networks:
    #   - frontend
    # depends_on:
    #   - redis
    # deploy:
    #   replicas: 2
    #   update_config:
    #     parallelism: 2
    #   restart_policy:
    #     condition: on-failure
  grafana:
    image: grafana/grafana
    # ports:
    #   - 5001:80
    # networks:
    #   - backend
    # depends_on:
    #   - db
    # deploy:
    #   replicas: 1
    #   update_config:
    #     parallelism: 2
    #     delay: 10s
    #   restart_policy:
    #     condition: on-failure
